version: '3.8'

services:
  price-service:
    image: $DOCKER_IMAGE
    restart: always
    environment:
      API:
      API_PATH:
      POSTGRES_HOST:
      POSTGRES_PORT:
      POSTGRES_USER:
      POSTGRES_DATABASE:
      POSTGRES_PASSWORD:
    ports:
      - "$DOCKER_PORT:3000"
  postgres:
    image: 'postgres:13-alpine'
    restart: always
    environment:
      POSTGRES_USER:
      POSTGRES_DATABASE:
      POSTGRES_PASSWORD:
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
